apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-infra-ca-issuer
  namespace: internal-infra-app
  labels:
    app: app
    component: ca-issuer
spec:
  ca:
    secretName: internal-infra-ca
